kata-ai/aksara-ui

src/assets/sass/vendor/react-dates.scss
src/components/DateRangePicker/DateRangePicker.tsx

DateRangePicker css is not imported

fix(style): DateRangePicker css

---

packages/form/README.md
packages/form/docs/index.mdx
packages/form/docs/props.ts
packages/form/examples/0-basic-example.raw.js
packages/form/examples/1-error-states.raw.js
packages/form/package.json
packages/form/src/components/FormError.tsx
packages/form/src/components/FormGroup.tsx
packages/form/src/components/FormLabel.tsx
packages/form/src/components/InputText.tsx
packages/form/src/components/InputTextarea.tsx
packages/form/src/index.ts
packages/form/src/styles.ts
packages/form/src/theme.ts
packages/form/src/themes/input.ts
packages/form/src/themes/label.ts
packages/form/tsconfig.build.json
packages/form/tsconfig.json
website/package.json
website/src/modules/demo/index.tsx
yarn.lock

feat(form): initialise inputtext + inputtextarea form

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

chore: added contributing guidelines + Code of Conduct

---

packages/drawer/package.json
packages/drawer/src/components/Drawer.tsx
packages/modal/package.json
packages/modal/src/components/Modal.tsx
yarn.lock

Uses [react-focus-lock](https://npmjs.com/package/react-focus-lock)
- feat: FocusLock on modal
- feat: FocusLock on drawer
For #41

Use focus lock

---

packages/button/src/components/Button.tsx
packages/button/src/components/FloatingButton.tsx
packages/button/src/components/SupportButton.tsx
packages/button/src/styles.ts
packages/modal/src/components/ModalHeader.tsx

We're going to normalise font sizes to ensure it won't be overriden by
global styles.

fix(button): font size normalisation

---

packages/drawer/__stories__/Drawer.story.tsx
packages/drawer/src/components/Drawer.tsx
packages/drawer/src/components/DrawerHeader.tsx
packages/modal/__stories__/Modal.story.tsx
packages/modal/src/components/Modal.tsx
packages/modal/src/components/ModalHeader.tsx

Fixes #63
Also updated stories for Drawer to include drawer overflow example

fix(drawer): fixed drawer overflow issue

---

packages/form/__stories__/Form.story.tsx
packages/form/src/components/FormGroup.tsx
packages/form/src/components/InputAddon.tsx
packages/form/src/components/InputGroup.tsx
packages/form/src/components/InputText.tsx
packages/form/src/index.ts
packages/form/src/styles.ts

feat(form): form addon

---

.storybook/__stories__/docs.story.tsx
.storybook/components/CodeBlock.tsx
.storybook/components/DocsElements.tsx
.storybook/components/DocsWrapper.tsx
.storybook/components/hljs-theme.ts
.storybook/config.js
.storybook/webpack.config.js
README.md
package.json
yarn.lock

TODO: add some documentation pages.

docs(storybook): allow Markdown stories

---

package.json
packages/react-select/README.md
packages/react-select/__stories__/Select.story.tsx
packages/react-select/package.json
packages/react-select/src/__tests__/Select.test.tsx
packages/react-select/src/components/SelectAsync.tsx
packages/react-select/src/components/SelectBase.tsx
packages/react-select/src/components/SelectCreatable.tsx
packages/react-select/src/index.ts
packages/react-select/src/styles.ts
packages/react-select/src/utils/createOption.ts
packages/react-select/tsconfig.json
packages/tsconfig.json
yarn.lock

New package which acts as a wrapper on top of `react-select` v2.

feat: react-select

---

packages/layout/src/components/SidebarSubMenu.tsx
packages/layout/src/components/Topbar.tsx

- make `icon` in SidebarSubMenu optional
- fixed submenu + topbar styles

fix(layout): layout fixes

---

.travis.yml
package.json

Added `moduleNameMapper` to match all modules w/ the listed package.
Also changed tests so it doesn't require build task.

test: fixed module not found errors

---

packages/modal/src/components/Modal.tsx

change `getDerivedStateFromProps` into `componentDidUpdate` for styled components to work

fix(modal): change to cDU for styled component

---

packages/layout/src/components/SidebarSubMenu.tsx

Minor alignment issue on `SidebarSubMenu` when using SVG icons. Fixed by moving to flexbox + increasing icon size

fix(layout): realign submenu SVG icons

---

packages/drawer/src/components/Drawer.stories.tsx
packages/drawer/src/components/Drawer.tsx

New prop in drawer to allow clicking of drawer overlay to close.

feat(drawer): new isOverlayClickable prop

---

packages/wicara-core/src/components/button/Button.stories.tsx
packages/wicara-core/src/components/button/Button.test.tsx
packages/wicara-core/src/components/button/FloatingButton.tsx
packages/wicara-core/src/components/button/README.md
packages/wicara-core/src/components/button/index.ts
packages/wicara-core/src/components/button/styles.ts
packages/wicara-core/src/components/button/utils/buttonUtils.ts
packages/wicara-core/src/components/button/utils/floatingButtonUtils.ts

feat(button): port floating button to wicara 0.8

---

packages/wicara-core/src/components/button/Button.stories.tsx
packages/wicara-core/src/components/button/FloatingButton.stories.tsx
packages/wicara-core/src/components/button/styles.ts
packages/wicara-core/src/components/button/utils/buttonUtils.ts

feat(button): added Inverse button variant

---

packages/wicara-core/package.json
packages/wicara-core/src/components/button/Button.test.tsx
packages/wicara-core/src/components/button/IconButton.stories.tsx
packages/wicara-core/src/components/button/IconButton.tsx
packages/wicara-core/src/components/button/README.md
packages/wicara-core/src/components/button/index.ts
packages/wicara-core/src/components/button/styles.ts
packages/wicara-core/src/components/button/utils/iconButtonUtils.ts
yarn.lock

feat(button): added IconButton

---

packages/wicara-core/src/components/button/README.md
packages/wicara-core/src/foundations/card/index.stories.tsx
packages/wicara-core/src/foundations/common/README.md
packages/wicara-core/src/foundations/common/components/UnstyledAnchor.test.tsx
packages/wicara-core/src/foundations/common/components/UnstyledAnchor.tsx
packages/wicara-core/src/foundations/common/components/UnstyledButton.test.tsx
packages/wicara-core/src/foundations/common/components/UnstyledButton.tsx
packages/wicara-core/src/foundations/common/components/index.ts
packages/wicara-core/src/foundations/common/index.stories.tsx
packages/wicara-core/src/foundations/common/index.ts

- UnstyledAnchor
- UnstyledButton

feat(common): add two new common components

---

packages/wicara-core/src/components/button/Button.stories.tsx
packages/wicara-core/src/components/button/Button.tsx
packages/wicara-core/src/components/button/utils/buttonUtils.ts
packages/wicara-core/src/components/loading/components/Circle.test.tsx
packages/wicara-core/src/components/loading/components/Circle.tsx
packages/wicara-core/src/components/loading/index.stories.tsx
packages/wicara-core/src/components/loading/index.ts

feat(button): added `isLoading` prop

---

packages/wicara-core/src/components/dialog/components/Dialog.tsx

update for dialog props so dialog's size can be customized

fix(dialog): add new width, maxWidth, height, and maxHeight props

---

packages/wicara-core/src/components/button/Button.test.tsx
packages/wicara-core/src/components/button/IconButton.stories.tsx
packages/wicara-core/src/components/button/README.md
packages/wicara-core/src/components/button/styles.ts
packages/wicara-core/src/components/button/types.ts
packages/wicara-core/src/components/button/utils/iconButtonUtils.ts

feat(button): additional icon button sizes

---

packages/wicara-core/src/foundations/common/README.md
packages/wicara-core/src/foundations/common/components/Inline/Inline.test.tsx
packages/wicara-core/src/foundations/common/components/Inline/Inline.tsx
packages/wicara-core/src/foundations/common/components/Inline/index.ts
packages/wicara-core/src/foundations/common/components/Stack/Stack.test.tsx
packages/wicara-core/src/foundations/common/components/Stack/Stack.tsx
packages/wicara-core/src/foundations/common/components/Stack/index.ts
packages/wicara-core/src/foundations/common/components/index.ts
packages/wicara-core/src/foundations/common/index.stories.tsx

feat(common): added Stack and Inline components

---

packages/wicara-core/package.json
packages/wicara-core/src/components/popover/README.md
packages/wicara-core/src/components/popover/components/Popover.stories.tsx
packages/wicara-core/src/components/popover/components/Popover.test.tsx
packages/wicara-core/src/components/popover/components/Popover.tsx
packages/wicara-core/src/components/popover/components/index.ts
packages/wicara-core/src/components/popover/index.ts
packages/wicara-core/src/components/popover/styles.ts
packages/wicara-core/src/jest.setup.ts
yarn.lock

feat(popover): add popover component

---

packages/aksara-ui-core/src/components/dropdown/README.md
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/DropdownMenu.test.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/DropdownMenu.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/index.ts
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/styles.ts
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuDivider.test.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuDivider.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuHeader.test.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuHeader.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.test.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/index.ts
packages/aksara-ui-core/src/components/dropdown/dropdown.stories.tsx
packages/aksara-ui-core/src/components/dropdown/index.ts

feat(dropdown): added DropdownMenu

---

packages/aksara-ui-core/src/components/non-ideal-state/README.md
packages/aksara-ui-core/src/components/non-ideal-state/components/Blankslate.stories.tsx
packages/aksara-ui-core/src/components/non-ideal-state/components/Blankslate.test.tsx
packages/aksara-ui-core/src/components/non-ideal-state/components/Blankslate.tsx
packages/aksara-ui-core/src/components/non-ideal-state/index.ts

refactor(blankslate): rename from NonIdealState

---

packages/aksara-ui-core/src/components/data-table/DataTable.stories.tsx
packages/aksara-ui-core/src/components/data-table/DataTable.test.tsx
packages/aksara-ui-core/src/components/data-table/README.md
packages/aksara-ui-core/src/components/data-table/components/Table/Table.tsx
packages/aksara-ui-core/src/components/data-table/components/Table/index.ts
packages/aksara-ui-core/src/components/data-table/components/TableBody/TableBody.tsx
packages/aksara-ui-core/src/components/data-table/components/TableBody/TableBodyCell.tsx
packages/aksara-ui-core/src/components/data-table/components/TableBody/TableBodyRow.tsx
packages/aksara-ui-core/src/components/data-table/components/TableBody/index.ts
packages/aksara-ui-core/src/components/data-table/components/TableContainer/TableContainer.tsx
packages/aksara-ui-core/src/components/data-table/components/TableContainer/index.ts
packages/aksara-ui-core/src/components/data-table/components/TableHead/TableHead.tsx
packages/aksara-ui-core/src/components/data-table/components/TableHead/TableHeadRow.tsx
packages/aksara-ui-core/src/components/data-table/components/TableHead/index.ts
packages/aksara-ui-core/src/components/data-table/components/TableHeader/TableHeaderCell.tsx
packages/aksara-ui-core/src/components/data-table/components/TableHeader/index.ts
packages/aksara-ui-core/src/components/data-table/components/index.ts
packages/aksara-ui-core/src/components/data-table/index.ts
packages/aksara-ui-core/src/components/data-table/styles.ts

feat(data-table): added data table component

---

README.md

docs: replace CodeClimate badge with SonarCloud

---

packages/aksara-ui-core/src/components/button-group/components/ButtonGroup/ButtonGroup.stories.tsx
packages/aksara-ui-core/src/components/button-group/components/ButtonGroup/ButtonGroup.tsx
packages/aksara-ui-core/src/components/button/Button.test.tsx
packages/aksara-ui-core/src/components/button/Button.tsx
packages/aksara-ui-core/src/components/button/IconButton.tsx
packages/aksara-ui-core/src/components/button/types.ts
packages/aksara-ui-core/src/components/button/utils/buttonUtils.ts

feat(button): add selected styles

---

packages/aksara-ui-core/src/components/index.ts
packages/aksara-ui-core/src/components/interactive-card/README.md
packages/aksara-ui-core/src/components/interactive-card/components/InteractiveCard/InteractiveCard.stories.tsx
packages/aksara-ui-core/src/components/interactive-card/components/InteractiveCard/InteractiveCard.test.tsx
packages/aksara-ui-core/src/components/interactive-card/components/InteractiveCard/InteractiveCard.tsx
packages/aksara-ui-core/src/components/interactive-card/components/InteractiveCard/index.ts
packages/aksara-ui-core/src/components/interactive-card/components/index.ts
packages/aksara-ui-core/src/components/interactive-card/index.ts

feat(interactive-card): add InteractiveCard component

---

package.json
packages/aksara-icons/package.json
packages/aksara-ui-core/@types/styled-system__should-forward-prop/index.d.ts
packages/aksara-ui-core/package.json
packages/aksara-ui-core/src/components/badge/components/__snapshots__/Badge.test.tsx.snap
packages/aksara-ui-core/src/components/data-table/components/TableBody/TableBodyCell.tsx
packages/aksara-ui-core/src/components/message/components/__snapshots__/Message.test.tsx.snap
packages/aksara-ui-core/src/foundations/box/components/Box.tsx
packages/aksara-ui-core/src/foundations/card/components/Card.tsx
packages/aksara-ui-core/src/foundations/typography/components/Heading.tsx
packages/aksara-ui-core/src/foundations/typography/components/Paragraph.tsx
packages/aksara-ui-core/src/foundations/typography/components/Text.tsx
packages/aksara-ui-core/src/foundations/typography/utils/index.ts
packages/aksara-ui-core/src/foundations/typography/utils/shouldForwardTextProp.ts
packages/aksara-ui-core/src/utils/primitives.ts
yarn.lock

BREAKING CHANGE: Requires `styled-components@5.1.0` or higher.

feat(foundations): implement shouldForwardProp

---

CONTRIBUTING.md

In case You wonder what looks like:
P.S please make sure the `git` version and the `yarn` version, are they legit? waiting for feedback
---
Aksara UI is an open source, so every component in Aksara UI is developed by your help. You too can help contribute to this project! This page describes how to setup the project on your computer for local development.
This project is bound by a [Code of Conduct](CODE_OF_CONDUCT.md).
The simple steps of contributing to any GitHub project are as follows:
1. [Fork the repository](https://github.com/kata-ai/aksara-ui/fork)
2. Create your feature branch: `git checkout -b my-new-feature`
3. Commit your changes: `git commit -am 'Add some feature'`
4. Push to the branch: `git push -u origin my-new-feature`
5. Create a [Pull …

docs: update contributing readme

---

.vscode/settings.json
packages/aksara-ui-core/package.json
packages/aksara-ui-core/src/components/collapsible/README.md
packages/aksara-ui-core/src/components/collapsible/components/Accordion/Accordion.stories.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/Accordion.test.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/Accordion.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/AccordionButton.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/AccordionItem.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/AccordionPanel.tsx
packages/aksara-ui-core/src/components/collapsible/components/Accordion/README.md
packages/aksara-ui-core/src/components/collapsible/components/Accordion/index.ts
packages/aksara-ui-core/src/components/collapsible/components/Accordion/styled.ts
packages/aksara-ui-core/src/components/collapsible/index.ts
yarn.lock

feat(collapsible): accordion component

---

packages/aksara-ui-core/src/components/avatar/components/Avatar.stories.tsx
packages/aksara-ui-core/src/components/avatar/styles.ts

fix(avatar): remove square layout

---

packages/aksara-ui-core/src/components/form/components/InputToggle/InputToggle.stories.tsx
packages/aksara-ui-core/src/components/form/components/InputToggle/InputToggle.test.tsx
packages/aksara-ui-core/src/components/form/components/InputToggle/InputToggle.tsx
packages/aksara-ui-core/src/components/form/components/InputToggle/index.ts
packages/aksara-ui-core/src/components/form/components/InputToggle/types.ts
packages/aksara-ui-core/src/components/form/components/InputToggle/utils.ts
packages/aksara-ui-core/src/components/form/components/index.ts

feat(form): toggle button

---

packages/aksara-ui-core/src/components/panel/components/Panel.stories.tsx
packages/aksara-ui-core/src/components/panel/components/Panel.test.tsx
packages/aksara-ui-core/src/components/panel/components/Panel.tsx
packages/aksara-ui-core/src/components/panel/components/PanelFooter.test.tsx
packages/aksara-ui-core/src/components/panel/components/PanelFooter.tsx
packages/aksara-ui-core/src/components/panel/components/PanelHeader.test.tsx
packages/aksara-ui-core/src/components/panel/components/PanelHeader.tsx
packages/aksara-ui-core/src/components/panel/index.ts

feat(panel): panel component

---

packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/DropdownMenu.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenu/styles.ts
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuHeader.test.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuHeader.tsx
packages/aksara-ui-core/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/aksara-ui-core/src/components/dropdown/dropdown.stories.tsx
packages/aksara-ui-core/src/components/popover/components/Popover.stories.tsx

fix(dropdown): wrap with `forwardRef` and allow passing `BoxProps`

---

packages/aksara-ui-core/src/components/notification/NotificationManager.tsx
packages/aksara-ui-core/src/components/notification/components/Toaster.tsx

fix(notification): fix z-index of toaster wrapper

---

packages/aksara-ui-core/src/foundations/common/components/Inline/Inline.tsx

fix(inline): don't forward spacing prop

---

packages/aksara-ui-core/src/components/index.ts
packages/aksara-ui-core/src/components/tabs/components/Tab.tsx
packages/aksara-ui-core/src/components/tabs/components/TabList.tsx
packages/aksara-ui-core/src/components/tabs/components/TabPanel.tsx
packages/aksara-ui-core/src/components/tabs/components/TabPanels.tsx
packages/aksara-ui-core/src/components/tabs/components/Tabs.stories.tsx
packages/aksara-ui-core/src/components/tabs/components/Tabs.test.tsx
packages/aksara-ui-core/src/components/tabs/components/Tabs.tsx
packages/aksara-ui-core/src/components/tabs/context.tsx
packages/aksara-ui-core/src/components/tabs/index.ts
packages/aksara-ui-core/src/components/tabs/styles.ts
packages/aksara-ui-core/src/components/tabs/variants.ts
packages/aksara-ui-core/src/foundations/common/components/UnstyledButton/UnstyledButton.tsx
packages/aksara-ui-core/src/foundations/common/components/UnstyledButton/index.ts

Closed  #266 
- Implement tabs component
- also export * from UnstyledButton

feat: implement tabs component

---

packages/aksara-ui-core/src/components/badge/README.md
packages/aksara-ui-core/src/components/badge/components/Badge.stories.tsx
packages/aksara-ui-core/src/components/badge/components/Badge.test.tsx
packages/aksara-ui-core/src/components/badge/components/Badge.tsx
packages/aksara-ui-core/src/components/badge/components/__snapshots__/Badge.test.tsx.snap

feat: badge with icon

---

packages/aksara-ui-core/src/components/loading/components/Circle.stories.tsx
packages/aksara-ui-core/src/components/loading/components/Spinner.stories.tsx
packages/aksara-ui-core/src/components/loading/components/Spinner.test.tsx
packages/aksara-ui-core/src/components/loading/components/Spinner.tsx
packages/aksara-ui-core/src/components/loading/index.ts

feat(loading): add spinner

---

packages/aksara-ui-core/src/components/side-sheet/components/SideSheetContent.tsx

create new box for sidesheetcontent

feat: new sidesheetcontent

---

packages/aksara-ui-core/src/components/blankslate/components/Blankslate.stories.tsx
packages/aksara-ui-core/src/components/blankslate/components/Blankslate.tsx

feat(blankslate): add section-level variant

---

MIGRATING.md

docs: updated migrating guidelines to 1.0

---

packages/aksara-ui-core/src/aksara-provider/AksaraProvider.tsx
packages/aksara-ui-core/src/components/blankslate/components/Blankslate.tsx
packages/aksara-ui-core/src/components/message/components/Message.tsx

refactor(react): remove deprecated components

---

packages/react/src/theme/variants/typography.ts

style(react): minor typography tweaks

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx
packages/react/src/components/avatar/components/__snapshots__/Avatar.test.tsx.snap

refactor(react): new avatar style

---

packages/react/src/components/badge/components/Badge.stories.tsx
packages/react/src/components/badge/components/Badge.test.tsx
packages/react/src/components/badge/components/Badge.tsx
packages/react/src/theme/componentStyles/badge.ts

refactor(react): redesign badge for 2.0

---

packages/react/src/theme/componentStyles/tooltip.ts

refactor(react): re-style tooltip

---

packages/react/src/components/form/styles.ts
packages/react/src/components/form/themes/checkbox.ts

refactor(react): re-style checkbox for 2.0

---

packages/react/src/components/loading/components/Circle.tsx
packages/react/src/components/loading/components/Spinner.stories.tsx
packages/react/src/components/loading/components/Spinner.tsx

refactor(react): tweak spinner color to match 2.0 design

---

packages/react/src/components/breadcrumb/Breadcrumb.stories.tsx
packages/react/src/components/breadcrumb/Breadcrumb.test.tsx
packages/react/src/components/breadcrumb/Breadcrumb.tsx
packages/react/src/components/breadcrumb/BreadcrumbItem.tsx
packages/react/src/components/breadcrumb/README.md
packages/react/src/components/breadcrumb/index.ts
packages/react/src/components/index.ts
packages/react/src/theme/componentStyles/breadcrumb.ts
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/typography.ts

feat(react): breadcrumb base

---

packages/react/src/components/button-group/components/ButtonGroup/ButtonGroup.stories.tsx
packages/react/src/components/button-group/components/ButtonGroup/ButtonGroup.tsx
packages/react/src/theme/componentStyles/button.ts

feat(react): button group 2.0

---

packages/react/src/components/navigation/components/PrimaryNavItem.stories.tsx
packages/react/src/components/navigation/components/PrimaryNavItem.test.tsx
packages/react/src/components/navigation/components/PrimaryNavItem.tsx
packages/react/src/components/navigation/index.ts
packages/react/src/layout/typography/components/UnstyledAnchor/index.ts
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/navigation.ts
packages/react/src/theme/componentStyles/typography.ts

feat(react): navigation primary item

---

packages/react/src/components/navigation/components/SecondaryNavItem.stories.tsx
packages/react/src/components/navigation/components/SecondaryNavItem.test.tsx
packages/react/src/components/navigation/components/SecondaryNavItem.tsx
packages/react/src/components/navigation/index.ts
packages/react/src/theme/componentStyles/navigation.ts

feat(react): secondary nav item

---

packages/react/src/components/tooltip/components/Tooltip.tsx
packages/react/src/components/tooltip/components/TooltipInner.tsx
packages/react/src/theme/componentStyles/tooltip.ts

fix(react): tooltip arrow

---

packages/react/src/components/tabs/components/Tab.tsx
packages/react/src/components/tabs/components/TabList.tsx
packages/react/src/components/tabs/styles.ts
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/tabs.ts

refactor(react): tabs 2.0

---

packages/react/src/components/badge/components/Badge.stories.tsx
packages/react/src/components/badge/components/Badge.test.tsx
packages/react/src/components/badge/components/Badge.tsx
packages/react/src/theme/componentStyles/badge.ts

refactor(react): rename badge colors

---

packages/react/src/components/tabs/components/Tab.tsx
packages/react/src/components/tabs/components/Tabs.stories.tsx
packages/react/src/theme/componentStyles/badge.ts
packages/react/src/theme/componentStyles/pill.ts
packages/react/src/theme/componentStyles/tabs.ts

fix(react): fix badge variants + tabs w/ icon

---

packages/react/src/theme/componentStyles/tabs.ts

fix(react): fixed tabs hover state

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx

fix(react): avatar icon sizes, with label variant

---

packages/react/src/layout/__stories__/Typography.stories.tsx
packages/react/src/stories/typography.stories.mdx

docs(react): fixed typography stories

---

packages/react/src/components/card/Card/Card.stories.tsx

fix(react): fixed avatar size on card header

---

packages/react/src/stories/typography.stories.mdx
packages/react/src/theme/componentStyles/typography.ts
packages/react/src/typography/__stories__/Typography.stories.tsx

fix(react): typography letter spacing fixes

---

packages/react/src/components/pill/components/Pill.stories.tsx
packages/react/src/theme/componentStyles/pill.ts

fix(react): fix color for default pill variant

---

packages/react/src/components/pill/components/Pill.tsx

fix(react): close icon size on pills

---

packages/react/src/components/button/components/Button/Button.stories.tsx
packages/react/src/components/button/components/Button/Button.tsx
packages/react/src/components/button/components/Button/ButtonAnchor.tsx
packages/react/src/components/button/components/Button/utils/renderButtonChildren.tsx
packages/react/src/components/button/components/Button/utils/renderButtonIcon.tsx
packages/react/src/components/button/components/PlainButton/PlainButton.stories.tsx
packages/react/src/components/button/components/PlainButton/PlainButton.tsx
packages/react/src/components/button/components/PlainButton/__snapshots__/PlainButton.test.tsx.snap
packages/react/src/components/button/components/PlainButton/types.tsx
packages/react/src/theme/componentStyles/button.ts

feat(react): button disclosure variant

---

packages/react/src/components/form/components/InputTags/InputTags.stories.tsx
packages/react/src/components/form/components/InputTags/InputTags.tsx
packages/react/src/components/form/components/InputTags/index.ts
packages/react/src/components/form/components/index.ts
packages/react/src/components/pill/components/Pill.stories.tsx
packages/react/src/components/pill/components/Pill.tsx
packages/react/src/theme/componentStyles/form.ts

feat(react): input tags

---

packages/react/src/components/toast/Toast.stories.tsx
packages/react/src/components/toast/internals/ToastContainer.tsx

fix(react): fix toast variant props & example error

---

packages/react/src/components/toast/Toast.stories.tsx
packages/react/src/components/toast/Toast.tsx
packages/react/src/theme/componentStyles/toast.ts

fix(react): toast font + button sizes

---

packages/react/src/components/empty-state/components/EmptyState.stories.tsx
packages/react/src/components/empty-state/components/EmptyState.tsx

feat(react): blankslate w/ icon styles

---

packages/react/src/components/loading/components/Circle.stories.tsx
packages/react/src/components/loading/components/Spinner.stories.tsx

fix(react): spinner color examples

---

packages/core/src/foundations/shadows.ts
packages/react/src/components/dialog/components/DialogContent.tsx
packages/react/src/components/dialog/components/DialogFooter.tsx
packages/react/src/components/dialog/components/DialogHeader.tsx
packages/react/src/components/dialog/components/DialogOverlay.tsx
packages/react/src/components/dialog/components/Modal.test.tsx
packages/react/src/components/dialog/components/Modal.tsx
packages/react/src/components/dialog/components/ModalHeaderIcon.tsx
packages/react/src/components/dialog/index.stories.tsx
packages/react/src/components/dialog/index.ts
packages/react/src/components/side-sheet/components/SideSheetFooter.tsx
packages/react/src/components/side-sheet/components/SideSheetHeader.tsx
packages/react/src/components/side-sheet/index.stories.tsx

feat(react): add newly design modal

---

packages/react/src/components/form/__stories__/InputCheckbox.stories.tsx

fix(react): checkbox label text

---

packages/react/src/components/form/__stories__/InputSearchbox.stories.tsx
packages/react/src/components/form/components/InputIcon/InputIconButton.tsx
packages/react/src/components/form/components/InputIcon/index.ts
packages/react/src/components/form/components/InputSearchbox/InputSearchbox.tsx
packages/react/src/components/form/components/InputSearchbox/index.ts
packages/react/src/components/form/components/InputText/InputText.tsx
packages/react/src/theme/componentStyles/form.ts

feat(react): input searchbox

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx

Fixes #384.
Add text size variations in avatar initials.

fix(react): adjust avatar initial text sizes

---

packages/react/src/theme/componentStyles/stepper.ts

related https://github.com/kata-ai/aksara-ui/issues/263

fix[react]: fixing stepper design

---

.husky/commit-msg
.husky/pre-commit
.huskyrc
package.json
yarn.lock

chore(react): upgrade husky + commitlint

---

packages/react/src/components/dropzone/components/Dropzone.test.tsx
packages/react/src/components/dropzone/components/UploadBox.tsx
packages/react/src/components/dropzone/components/Uploading.tsx
packages/react/src/components/dropzone/dropzone.stories.tsx

Closes #491 
- Update fix from latest comment https://github.com/kata-ai/aksara-ui/issues/491#issuecomment-958600514

fix: update fix for dropzone

---

package.json
packages/react/src/components/breadcrumb/Breadcrumb.tsx
packages/react/src/components/page-header/components/FilterPageHeader.tsx
packages/react/src/components/popover/README.md
packages/react/src/components/popover/components/Popover.stories.tsx
packages/react/src/components/popover/components/Popover.test.tsx
packages/react/src/components/popover/components/Popover.tsx
packages/react/src/components/popover/components/index.ts
packages/react/src/components/topbar/Topbar.stories.tsx
yarn.lock

Refactor structure of `Popover` to make `PopoverContent` extracted into its own component.

refactor(react): extract `PopoverContent` into its own component

---

packages/react/src/components/breadcrumb/Breadcrumb.tsx
packages/react/src/components/page-header/components/FilterPageHeader.tsx
packages/react/src/components/popover/README.md
packages/react/src/components/popover/components/Popover.stories.tsx
packages/react/src/components/popover/components/Popover.test.tsx
packages/react/src/components/popover/components/Popover.tsx
packages/react/src/components/topbar/Topbar.stories.tsx

Extract `PopoverTrigger` into its own component.

refactor(react): extract `PopoverTrigger` into its own component

---

packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelectSearch/InputSelectSearch.tsx
packages/react/src/theme/componentStyles/form.ts
packages/react/src/theme/componentStyles/form/select.ts

Closes #451
tweak focus styles on select fields

refactor(react): tweak focus styles on select fields

---

packages/react/src/components/form/components/InputSelectTags/InputSelectTags.tsx

Fixes #451.
Fixes focus issue on input select tags.

fix(react): fix focus variants on select tags

---

.vscode/settings.json
packages/react/src/components/pagination/components/Pagination.tsx
packages/react/src/components/pagination/components/PaginationButton.tsx
packages/react/src/components/pagination/components/PaginationJumpTo.tsx
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/pagination.ts

Closes #534
Add `PaginationJumpTo` component

feat(react): pagination JumpTo

---

packages/react/src/components/popover/components/Popover.tsx

Add an option to disable arrow in popover.

feat(react): popover content without arrow

---

packages/react/src/theme/componentStyles/pagination.ts

fix: fixing paginatio button style

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx
packages/react/src/components/avatar/components/Presence.tsx
packages/react/src/theme/componentStyles/avatar.ts
packages/react/src/theme/componentStyles/index.ts

feat(avatar): add presence option

---

lint-staged.config.js
package.json
packages/react/package.json
packages/react/src/components/dropdown/components/DropdownMenu/DropdownMenu.test.tsx
packages/react/src/components/dropdown/components/DropdownMenu/DropdownMenu.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuContent.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuDivider.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuHeader.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.test.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuTrigerer.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/index.ts
packages/react/src/components/dropdown/dropdown.stories.tsx
yarn.lock

feat: dropdown

---

packages/react/src/components/pagination/components/Pagination.tsx
packages/react/src/theme/componentStyles/pagination.ts

fix(pagination): adding space

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx
packages/react/src/components/avatar/components/Presence.tsx
packages/react/src/components/card/Card/Card.stories.tsx
packages/react/src/components/topbar/Topbar.stories.tsx
packages/react/src/theme/componentStyles/avatar.ts
packages/react/src/theme/componentStyles/topbar.ts

feat(avatar): update avatar story and avatar presence

---

packages/react/src/theme/componentStyles/avatar.ts

#566 
fix padding avatar presence at md lg size

feat(avatar): presence size adjusment

---

packages/react/src/components/topbar/Topbar.stories.tsx
packages/react/src/theme/componentStyles/topbar.ts

feat(topbar): update height

---

packages/react/src/components/filter-kit/FilterKit.stories.tsx
packages/react/src/components/filter-kit/FilterKit.tsx
packages/react/src/components/filter-kit/Filterkit.test.tsx
packages/react/src/components/filter-kit/index.ts
packages/react/src/components/page-header/PageHeader.stories.tsx
packages/react/src/components/page-header/PageHeader.tsx
packages/react/src/components/page-header/components/index.ts
packages/react/src/components/page-header/index.ts

feat(react): filter-kit and page-header

---

packages/react/src/components/avatar/components/Avatar.test.tsx
packages/react/src/components/avatar/components/Avatar.tsx
packages/react/src/components/avatar/components/Presence.tsx

test(avatar): adding presence test

---

packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelectSearch/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelectTags/InputSelectTags.tsx
packages/react/src/theme/componentStyles/form/select.ts

style(select): adjust padding

---

packages/react/src/helpers/portal/components/Portal.tsx
packages/react/src/utils/index.ts
packages/react/src/utils/useOnMount.ts

fix(react): address SSR error in portal

---

packages/react/src/components/message/components/Message.tsx

fix(react): change icon variant at message component

---

packages/react/src/theme/componentStyles/button.ts

fix(react): button active style

---

packages/react/src/components/dropdown/components/DropdownMenuItem/ActionList.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/react/src/components/dropdown/dropdown.stories.tsx
packages/react/src/components/pagination/components/Pagination.stories.tsx
packages/react/src/components/pagination/components/PaginationFilter.test.tsx
packages/react/src/components/pagination/components/PaginationFilter.tsx

fix: fix button variant at pagination filter
Closes #597 #462

feat(react): add actionList

---

packages/react/src/components/navigation/components/SecondaryNavItem.stories.tsx
packages/react/src/components/navigation/components/SecondaryNavItem.tsx

fix(react): secondary navigation disclosure

---

packages/react/src/theme/componentStyles/navigation.ts

feat(react): navigation use color greydark02

---

packages/react/src/theme/componentStyles/card.ts

fix(react): card use 8px radius

---

packages/react/src/theme/componentStyles/button.ts

#601 
fixing styled when button pressed

fix(react): update style at pressed secondary button

---

packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuContent.tsx
packages/react/src/components/dropdown/dropdown.stories.tsx

fix(react): dropdown action 

---

packages/react/src/components/button/components/Button/Button.stories.tsx
packages/react/src/components/button/components/Button/Button.tsx
packages/react/src/theme/componentStyles/button.ts

Closes #601 
use selected props to indicate button is selected / is actived

feat(react): add selected style to secondary button

---

packages/react/src/components/actionList/components/ActionListItem.tsx

fix(react): fix isActive actionList item style

---

packages/react/src/components/form/__stories__/InputSelect.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelectTags/InputSelectTags.tsx

fix(react): input select

---

packages/react/src/components/saveBar/components/SaveBar.stories.tsx
packages/react/src/components/saveBar/components/SaveBar.test.tsx
packages/react/src/components/saveBar/components/SaveBar.tsx
packages/react/src/components/saveBar/index.ts
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/saveBar.ts

feat(react): savebar

---

packages/react/src/components/form/components/InputSelect/InputSelect.tsx

fix(react): input select reset value onclose

---

packages/react/src/components/button/components/Button/types.ts
packages/react/src/components/button/components/Button/utils/renderButtonChildren.tsx
packages/react/src/theme/componentStyles/button.ts

fix(button): fix button outline desctuctive

---

packages/react/src/components/listResource/components/List.stories.tsx
packages/react/src/components/listResource/components/List.test.tsx
packages/react/src/components/listResource/components/List.tsx
packages/react/src/components/listResource/components/ListHeader.tsx
packages/react/src/components/listResource/components/ListItem.tsx
packages/react/src/components/listResource/index.ts
packages/react/src/theme/componentStyles/index.ts
packages/react/src/theme/componentStyles/list.ts

feat(list): add list component

---

packages/react/src/components/listResource/components/List.stories.tsx

docs: add storybook list with select item

---

packages/react/src/components/saveBar/components/SaveBar.stories.tsx
packages/react/src/components/saveBar/components/SaveBar.tsx
packages/react/src/components/topbar/Topbar.stories.tsx

feat: add icon at topbar and savebar

---

packages/react/src/components/form/components/InputSelect/InputSelect.tsx

fix: input select zindex

---

packages/react/src/components/form/styles.ts
packages/react/src/components/form/themes/checkbox.ts
packages/react/src/components/list-resource/components/List.stories.tsx
packages/react/src/components/saveBar/components/SaveBar.stories.tsx
packages/react/src/components/topbar/Topbar.stories.tsx
packages/react/src/theme/component-styles/list.ts

Closes #430 
Closes #626 
Closes #568 
Closes #391

style: update style

---

packages/react/src/theme/component-styles/list.ts

style: change text color List

---

packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/react/src/components/dropdown/dropdown.stories.tsx

feat(dropdown): remove marginX from DropdownMenuItem

---

packages/react/package.json
packages/react/src/components/form/__stories__/InputSelect/InputSelect.stories.tsx
packages/react/src/components/form/__stories__/InputSelect/InputSelectVirtualized.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelectVirtualized.tsx
packages/react/src/components/form/components/InputSelect/index.ts
yarn.lock

feat(input-select): input select virtualized

---

packages/react/src/components/overlay/components/OverlayScreen.stories.tsx
packages/react/src/components/overlay/components/OverlayScreen.tsx

feat(overlay): add backdrop-filter support

---

packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelect/InputSelectVirtualized.tsx

fix(input-select): fix highlighted index

---

packages/react/src/components/modal/components/Modal.tsx
packages/react/src/components/side-sheet/components/SideSheet.tsx

modal and sidesheet doens't have control to change backdrop blur effect before.
use same props from Overlay component ,backdropBlur , to change blur effect options

fix(react): add backdrop blur control to modal and sideSheet

---

packages/react/src/components/filter-kit/index.ts

change export name from FilterPageHeader to FilterKit

fix(filterkit): update export naming

---

packages/react/src/components/box-header-footer/components/BoxHeader.tsx

style(box-header): style focus at close button

---

packages/react/src/components/box-header-footer/BoxFooter.stories.tsx
packages/react/src/components/box-header-footer/BoxHeader.stories.tsx

docs: add box footer and box header documentation

---

packages/react/src/components/box-header-footer/BoxFooter.stories.tsx
packages/react/src/components/box-header-footer/BoxHeader.stories.tsx
packages/react/src/components/modal/components/ModalHeaderIcon.tsx
packages/react/src/theme/component-styles/box-header-footer.ts

docs: box-header-footer storybook update

---

packages/react/src/components/form/components/InputTags/InputTags.tsx

fix(input-tags): prevent enter keys from submiting form

---

packages/react/src/components/form/__stories__/RadioGroup.stories.tsx
packages/react/src/components/form/components/RadioGroup/RadioGroup.tsx

feat: wip radio group

---

packages/react/src/components/form/__stories__/InputSelect/InputSelectSearch.stories.tsx
packages/react/src/components/form/__stories__/InputSelect/InputSelectSearchVirtualized.stories.tsx
packages/react/src/components/form/__stories__/InputSelectTag.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearchVirtualized.tsx
packages/react/src/components/form/components/InputSelectTags/InputSelectTags.tsx

fix: input tag select action and remove openOnFocus props

---

packages/react/src/components/side-sheet/components/SideSheetContent.tsx

feat: adjust padding sidesheet component

---

packages/react/src/components/box-header-footer/components/BoxFooter.tsx

style(box-footer): fix caption font style

---

packages/react/src/components/side-sheet/components/SideSheet.tsx
packages/react/src/components/side-sheet/components/SideSheetContent.tsx
packages/react/src/components/side-sheet/index.stories.tsx

style(side-sheet): update style side-sheet seperator

---

packages/react/src/components/accordion/components/Accordion.stories.tsx
packages/react/src/components/accordion/components/Accordion.tsx

fix: accordion variant size

---

packages/react/src/components/accordion/components/Accordion.stories.tsx
packages/react/src/components/accordion/components/Accordion.tsx

refactor accordion to use less code

refactor: accordion

---

packages/react/src/theme/component-styles/navigation.ts

fix(navigation): make focus-visible similar to focus css

---

packages/react/src/components/pagination/components/Pagination.stories.tsx
packages/react/src/components/pagination/components/PaginationDetail.test.tsx
packages/react/src/components/pagination/components/PaginationDetail.tsx

fix: pagination-detail pagination info

---

packages/react/src/components/date-picker/DatePicker.stories.tsx
packages/react/src/components/date-picker/DatePicker.tsx
packages/react/src/components/date-picker/components/Calendar.tsx

fix: range picker value

---

packages/react/src/components/date-picker/DatePicker.stories.tsx
packages/react/src/components/date-picker/DatePicker.tsx
packages/react/src/components/date-picker/components/Calendar.tsx
packages/react/src/theme/component-styles/datepicker.ts

style: date picker

---

packages/react/src/components/action-list/actionList.stories.tsx

docs: add ActionListItem with icon

---

packages/react/src/components/save-bar/components/SaveBar.stories.tsx
packages/react/src/components/save-bar/components/SaveBar.test.tsx
packages/react/src/components/save-bar/components/SaveBar.tsx

feat: show savebar using portal

---

packages/react/src/components/action-list/actionList.stories.tsx
packages/react/src/components/action-list/components/ActionListItem.tsx
packages/react/src/theme/component-styles/action-list.ts

feat(actionListItem): add destructive variant

---

packages/react/src/components/form/__stories__/InputSelect/InputSelect.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelect.tsx

docs: add input select with prefix

---

packages/react/src/components/date-picker/AdvancedOption.tsx
packages/react/src/components/date-picker/DatePicker.stories.tsx
packages/react/src/components/date-picker/DatePicker.test.tsx
packages/react/src/components/date-picker/components/Calendar.tsx

test: date picker

---

packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/react/src/components/pagination/components/Pagination.stories.tsx
packages/react/src/components/pagination/components/PaginationFilter.tsx

fix: pagination filter style

---

packages/react/src/components/date-picker/DatePicker.stories.tsx

fix: remove nubbin from datepicker container

---

packages/react/src/components/form/__stories__/InputSelect/InputSelect.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearchVirtualized.tsx

feat: update input selecte option component #717

---

packages/react/src/components/avatar/components/Avatar.stories.tsx
packages/react/src/components/avatar/components/Avatar.tsx
packages/react/test/setupTests.ts

feat: avatar bg randomizer based on name value

---

packages/react/src/components/form/__stories__/InputSelect/InputSelect.stories.tsx
packages/react/src/components/form/__stories__/InputSelect/InputSelectSearch.stories.tsx
packages/react/src/components/form/__stories__/InputSelect/InputSelectSearchVirtualized.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearchVirtualized.tsx

fix: input select 

---

packages/react/src/components/save-bar/components/SaveBar.tsx

feat: savebar fade-in fade-out transition

---

packages/react/src/components/action-list/components/ActionListItem.tsx
packages/react/src/components/dropdown/components/DropdownMenu/DropdownMenu.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuContent.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuItem.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuTrigger.tsx
packages/react/src/components/dropdown/dropdown.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelect.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearchVirtualized.tsx
packages/react/src/components/form/components/InputSelectTags/InputSelectTags.tsx
packages/react/src/components/pagination/components/PaginationFilter.tsx

fix: dropdown

---

packages/react/src/components/box-header-footer/BoxHeader.stories.tsx
packages/react/src/components/modal/components/ModalHeaderIcon.tsx
packages/react/src/components/modal/index.stories.tsx

fix: icon bgColor and color props

---

packages/react/src/components/button/components/IconButton/IconButton.stories.tsx
packages/react/src/components/button/components/IconButton/IconButton.tsx
packages/react/src/components/button/components/PlainButton/PlainButton.stories.tsx
packages/react/src/components/button/components/PlainButton/PlainButton.tsx
packages/react/src/theme/component-styles/button.ts

style: button icon and plain selected style

---

packages/core/src/foundations/shadows.ts
packages/react/src/components/card/Card/Card.stories.tsx
packages/react/src/components/dropdown/components/DropdownMenuItem/DropdownMenuContent.tsx
packages/react/src/components/popover/components/Popover.tsx

feat: use filter drop shadow

---

packages/react/src/components/form/__stories__/InputSelect/InputSelectSearch.stories.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearch.tsx
packages/react/src/components/form/components/InputSelect/InputSelectSearchVirtualized.tsx

fix: inputSelect input value click behaviour

---

packages/react/src/components/filter-kit/FilterKit.tsx

feat: add prefix at input select

---

packages/react/src/components/action-list/ActionList.stories.tsx

docs: add story about action list with desc

---

packages/react/src/components/list-resource/components/List.stories.tsx
packages/react/src/components/table/Table.stories.tsx

update ideterminate handler on list resource and table

docs: change indeterminate handler

---

packages/react/src/theme/component-styles/button.ts

style: button destructive hover and pressed style

---

packages/react/src/components/form/components/InputTags/InputTags.tsx

feat(input-tags): paste handler

---

packages/react/src/components/badge/components/Badge.stories.tsx
packages/react/src/components/badge/components/Badge.tsx
packages/react/src/theme/component-styles/badge.ts

fix(badge): remove lg variant

---

packages/react/src/components/filter-kit/FilterKit.tsx
packages/react/src/components/tag/components/Tag.stories.tsx
packages/react/src/components/tag/components/Tag.tsx
packages/react/src/theme/component-styles/tag.ts

fix(tag): selected props

---

packages/react/package.json
packages/react/src/components/navigation/components/DisclosureNavItem.stories.tsx
packages/react/src/components/navigation/components/DisclosureNavItem.test.tsx
packages/react/src/components/navigation/components/DisclosureNavItem.tsx
packages/react/src/components/navigation/components/SecondaryNavItem.stories.tsx
packages/react/src/components/navigation/components/SecondaryNavItem.tsx
packages/react/src/theme/component-styles/navigation.ts
yarn.lock

feat(navigation): disclosure navigation
