src/components/Card/__tests__/Card.spec.tsx, src/components/Card/index.tsx
before:
because in file `components/index.tsx` export all from imports while file `components/Card/index.tsx` export with default so kata-kit has as whole does not have exported member named `Card` .
fix:
change `export default` to `export {}`
=> fix(card): change export mode from default to module in card component

packages/pagination/src/Pagination.tsx
Ellipsis pages can't be selected anyway, so it's better to set those
buttons to `disabled`.
=> fix(pagination): page buttons w/ ellipsis should be disabled

packages/layout/src/SidebarMain.tsx, packages/layout/src/SidebarMainMenu.tsx, packages/layout/src/SidebarSubMenu.tsx, packages/reset/src/base/_globals.scss, packages/theme/src/constants.ts
Adds styling reset for `a:focus` (for accessibility purposes). Also tweaked some `@kata-kit/layout` styles that gets affected directly by this PR.
EDIT: Adding demo screenshot.
=> style(reset): add focus theme reset

packages/button/src/components/ToggleButton.tsx
Closes #35
This bug caused by the wrong use of `getDerivedStateFromProps`. Actually, we don't need that method to maintain the component state.
=> fix(toggle-button): wrong state

package.json, yarn.lock
Adds prettier as a dependency because tslint needs it to run
For #49
=> fix: be able to use tslint in command line

packages/common/docs/index.mdx, packages/common/docs/props.ts, packages/common/examples/3-focus-trap.raw.js, packages/common/package.json, packages/common/src/FocusTrap.tsx, packages/common/src/index.ts, packages/drawer/package.json, packages/drawer/src/components/Drawer.tsx, packages/drawer/tsconfig.json, packages/modal/package.json, packages/modal/src/components/Modal.tsx, packages/modal/tsconfig.json, yarn.lock
For #41 
Very happy with this solution. Includes a new component using `focus-trap`. (seems like the best library, reach-ui also uses this)
Changed `Modal` and `Drawer` to use the new component. Also made them close when pressing Escape
Preview of the changes: http://hanging-face.surge.sh/components/common http://hanging-face.surge.sh/components/modal http://hanging-face.surge.sh/components/drawer
=> New focus trap component

.storybook/webpack.config.js, package.json, yarn.lock
This speeds up the build time, since `awesome-typescript-loader` normally does type checking on the same process
Doesn't seem to affect the start up time too much, but definitely affects the hot reload time.
Before: https://i.imgur.com/mFcJPk9.png (62s)
After: https://i.imgur.com/NiLQ8VI.png (6s)
=> build: use `fork-ts-checker-webpack-plugin` for type checking

__stories__/2-components/button/Button.story.tsx, packages/button/src/__tests__/HollowButton.test.tsx, packages/button/src/__tests__/IconicButton.test.tsx, packages/button/src/components/Button.tsx, packages/button/src/components/HollowButton.tsx, packages/button/src/components/IconicButton.tsx, packages/button/src/helpers.ts, packages/button/src/index.ts
Added two new button types, `HollowButton` and `IconicButton`.
**HollowButton**
**IconicButton**
=>  feat(button): added new HollowButton + IconicButton styles

packages/layout/README.md, packages/layout/src/__tests__/Layout.tsx, packages/layout/src/components/SidebarMainMenu.tsx, packages/layout/src/components/SidebarSub.tsx, packages/layout/src/components/SidebarSubMenu.tsx
Turns out we still need `react-router-dom` for layout after all. This
allows the sidebar main/sub menus to be a NavLink with `asNavLink`.
This reverts the fixes made in #46.
=> fix(layout): optionally allow menus to be NavLink

packages/layout/src/components/SidebarSubMenu.tsx
When a link is clicked in `SidebarSubMenu`, it should've looked like this:
However, we forgot to set the background color...
=> fix(layout): fixed active state in SidebarSubMenu

__mocks__/lodash-es/add.ts, packages/common/src/components/Skeleton/Skeleton.tsx, packages/dropdown/package.json, packages/dropdown/src/components/Dropdown.tsx, packages/dropdown/src/components/DropdownToggle.tsx, packages/pagination/package.json, packages/pagination/src/Pagination.tsx, packages/tooltip/package.json, packages/tooltip/src/components/Tooltip.tsx, packages/tooltip/src/components/TooltipTarget.tsx, yarn.lock
Some `lodash` uses can already be replaced by its vanilla counterparts,
so let's use that.
=> refactor: cleanup some uses of lodash

packages/common/package.json, packages/common/src/components/EmptyMessage/EmptyMessage.tsx
When no image is passed, `EmptyMessage` should show no image at all or no fallback assets from `@wicara/assets` should be pulled.
=> feat(common): make EmptyMessage images optional

packages/drawer/src/components/Drawer.tsx, packages/modal/src/__tests__/Modal.test.tsx, packages/modal/src/components/Modal.tsx
The `FocusTrap` helper component has been giving issues on some use
cases, e.g. file inputs. We added an additional prop to allow optionally
disabling said focus trap.
=> fix(modal): allow temporarily disabling focus trap

packages/wicara-core/src/Theme.tsx, packages/wicara-core/src/components/dialog/components/Dialog.tsx, packages/wicara-core/src/components/side-sheet/components/SideSheet.tsx, packages/wicara-core/src/foundations/box/components/Box.tsx, packages/wicara-core/src/foundations/card/components/Card.tsx, packages/wicara-core/src/foundations/card/index.stories.tsx, packages/wicara-core/src/utils/variables.ts
This PR refactors some of the `Box` + `Card` functionalities to support
the `elevation` prop using `styled-system`'s `variant` API.
Fixes #172
=> feat(card): support `elevation` prop

packages/aksara-ui-core/src/utils/storybook/SystemHeader.tsx, packages/aksara-ui-core/src/utils/variables.ts
BREAKING CHANGES: `barlow` font theme token has been renamed to `brand`.
=> fix(utils): rename brand fonts token to `brand`

packages/aksara-ui-core/src/foundations/reset/styles/normalize.ts
This should prevent Jest from spitting out the "Could not parse
stylesheet" errors that we keep getting.
=> fix(reset): remove `!` in modern-normalize header comment

packages/aksara-ui-core/src/components/button/Button.stories.tsx, packages/aksara-ui-core/src/components/button/Button.test.tsx, packages/aksara-ui-core/src/components/button/Button.tsx, packages/aksara-ui-core/src/components/button/FloatingButton.stories.tsx, packages/aksara-ui-core/src/components/button/FloatingButton.tsx, packages/aksara-ui-core/src/components/button/IconButton.stories.tsx, packages/aksara-ui-core/src/components/button/OutlineButton.stories.tsx, packages/aksara-ui-core/src/components/button/OutlineButton.tsx, packages/aksara-ui-core/src/components/button/components/LinkButton/LinkButton.tsx, packages/aksara-ui-core/src/components/button/components/LinkButton/styles.tsx, packages/aksara-ui-core/src/components/button/components/LinkButton/variants.ts, packages/aksara-ui-core/src/components/button/styles.ts, packages/aksara-ui-core/src/components/button/types.ts, packages/aksara-ui-core/src/components/button/utils/floatingButtonUtils.ts, packages/aksara-ui-core/src/components/button/utils/iconButtonUtils.ts, packages/aksara-ui-core/src/foundations/card/index.stories.tsx
BREAKING CHANGES: Button now uses number-based size props instead of
token-based size props.
=> refactor(button): switch from token sizing to number sizing

packages/aksara-ui-core/package.json, yarn.lock
I accidentally removed `@types/styled-components` on a previous PR. This
PR adds it back.
=> fix: re-add styled-components types

packages/aksara-ui-core/src/components/blankslate/components/Blankslate.stories.tsx, packages/aksara-ui-core/src/components/blankslate/components/Blankslate.test.tsx, packages/aksara-ui-core/src/components/blankslate/components/Blankslate.tsx
New blankslate variants:
- Page level (`variant="page"`)
- Inner level (`variant="inner"`)
Fixes #243.
=> feat(blankslate): add additional blankslate variants

packages/aksara-ui-core/src/components/dialog/components/Dialog.test.tsx, packages/aksara-ui-core/src/components/side-sheet/components/SideSheet.test.tsx, packages/aksara-ui-core/src/foundations/portal/components/Portal.tsx
BREAKING CHANGE: Any DOM query that calls `data-wicara-portal` will need
to be changed to the new data-attribute.
=> refactor(portal): `data-wicara-portal` -> `data-aksara-portal`

packages/aksara-ui-core/src/components/tooltip/components/TooltipInner.tsx
Fixes the issue where the tooltip sometimes appears behind an element
with a higher z-index.
Fixes #287.
=> fix(tooltip): use proper z-index on tooltip wrapper

packages/aksara-ui-core/src/components/tabs/index.ts
There are missing import in around of `Tabs component` .
So by this PR, I want to fix it.
=> fix: missing import around tabs component

packages/aksara-ui-core/src/foundations/common/components/UnstyledAnchor/UnstyledAnchor.tsx, packages/aksara-ui-core/src/foundations/common/components/UnstyledButton/UnstyledButton.tsx, packages/aksara-ui-core/src/theme/componentStyles/button.ts, packages/aksara-ui-core/src/theme/componentStyles/index.ts, packages/aksara-ui-core/src/theme/componentStyles/typography.ts
Allow passing pseudo + `sx` props in these components:
- `UnstyledButton`
- `UnstyledAnchor`
=> refactor: allow passing pseudo + `sx` props in more components

packages/aksara-ui-core/src/components/form/components/FormGroup/FormGroup.tsx, packages/aksara-ui-core/src/layout/inline/Inline.tsx, packages/aksara-ui-core/src/layout/stack/Stack.tsx
Deprecated the following components:
- `FormGroup` - use `<Stack spacing="xs" />` instead.
- `Inline` - This component will soon be replaced with `<Stack direction="row" />`
=> refactor: deprecated `FormGroup` and `Inline`

packages/react/package.json, packages/react/src/components/popover/components/Popover.stories.tsx, packages/react/src/components/popover/components/Popover.test.tsx, packages/react/src/components/popover/components/Popover.tsx, packages/react/src/components/tooltip/components/TooltipInner.tsx, packages/react/src/theme/componentStyles/index.ts, packages/react/src/theme/componentStyles/popover.ts, packages/react/test/setupTests.ts, yarn.lock
Closes #495
Closes #496
Migrates `Popover` to `radix-ui` to fix all the issues
=> refactor(react): migrate `Popover` to `radix-ui`

packages/react/src/aksara-provider/AksaraProvider.tsx, packages/react/src/components/toast/README.md, packages/react/src/components/toast/ToastProvider.tsx, packages/react/src/components/toast/index.ts, packages/react/src/components/toast/internals/index.ts
Move `ToastProvider` outside of internals in preparation of requiring users to import `ToastProvider` explicitly.
=> refactor(toast): move `ToastProvider` outside of internals

packages/react/src/components/form/components/InputSelect/InputSelect.tsx
Use `overflow: auto` instead of `overflow: scroll` to prevent unintended scroller.
=> fix(react): fixed input select scroll overflow
